/*======================================================================================================================================================================================================
0KXK00000000000000KX0000000000KK00KXK000000000K0000KK000000000KKK0KNMMMMMMKc',;ldccxNMMMWWNX0O0WMNXNWWWWWNOx0NXOxdxOKNWWWWWWWWWWWWWWWWWWNNNWWWNOxddoooood0WMWWWWWXOOKXNWWWXKNKo::;::;,;xNWNWMMWNWWMWNXXK
00K0000KKKK0000000KK000KK000000000KK000KK0000000000KK000KK00000000NWMMMMMXo,',;::ckNMMMWWNX0OKWMW0dxkOKNWXkxKWWNX0K00NWWWWWWWWWWWWWWWWWWWNNWWWWXkddooooooxXWWWWWWWN0O0XNWNOkO0koc:clc::lkO0XXXK0KXNNXXKK
000000000XNXKK000000000000O0K00O00000000K000KK0000000000KK000KK00XWMMMMMKo;',:c:l0WMMMWWNKO0NMMMWOoooodxOOxONWWNNXXOkXWWWWWWWWWWNNWWWWWNNNXNWWWWKxoodx0KxoxXWWWN0OXWX0OKXXOkkkOOxlclllllllodxkO0000000OK
KK000K000XWNK000KKK00KK0OOOOOOOO0K0O00K0000000000KK0000000000000XWMMMMMKl,',;:cdKWMMMWNX0O0NMMMMXxloooooddxKWWWNNXKOxKWWWWWWWWWNNNNWWWWNNNNXXNWWNKOOKNNNKxoxKKkdooONMWKO0KOOkkkO0Ooc::ccccccccox0KXXNNNW
0000KXXXNWMWNXXXK0000KK0OO00OOOOOOOO0KKK000K0000000000KK0000000XWMMMMMXd:,,;::dKMMMWWNX0OKWWWWWW0oldddooooxXWWWNXKKOdONNNWWWWWNNNNNNWWWNNNNKKXNWWWWWWWNNX0dloocclod0WWWKOkkkO0XNWMXxc:cccccccc::coxOXWMM
00000KKKKNMNXKXXK00000OOOO00OO0K0OO0KXK0000K000KK0000000000KK0KWMMMMMKl,,,;:cxXMMMWWNX0OXWWWWWWNklx0XKOxddONWWWNXK0OdxXNNWWWWWNXNNNXNWWNNXXXO0XNWWWWWWWNXKklclc:coodKWWNK0kOXNWWMMMNkc::::::::::::;:okKW
000KK000KNWN00000O0KK0OOOO0OOO000OO0XXK0OOOO000KK000KK0000000KNMMMMMXd;,,;;:dXMMMWWNX0ONWK0XNWWKdlONWWWNXXNWWWWXX0kkdo0NNNWWWWNXXNNXKNWNNXXXOx0XNNNNWWWWNX0xccccclooxKNXKkddOXNWWMMMW0l:::::::::::::;;co
0000000KXNWXKK0OOOOOOOOOKXNX000OOOOO00OOO00000000000KK000KK0KNWMMMMNx:;;;;:oKWMMWWNXOOXMNkodxkOxlo0WWWWWWWWWWWXKKOxxdokXXXNWWNNKXNNK0XWNNXKK0xx0XNNNNNWWNX0koccclx0kdxK0kddookKNWWWMMW0o:::::::::::::::;
0KK000000KXKKK0OO00OOO0KXNWNXXK0O000000OOO000KKK000000000KXNWMMMMMXx:;;;::l0WMMWWNX0OXWMXxolc::ccdXWWWWWWNNNWNKOKOdddod0XKNNNNX0KNNKk0WNNXK00kokKKXNNNNWNX0OxdoxOKXKxoddooooooxKNWWMMMWKo:::::::::::::::
0KK00KXK00KK00OOO00OOO0K0XWX00000KXXKKKKKKKKKKKK00KKK00KXNWMMMMWKxl:;::::ckNMMMWNX0k0NWW0dol::::ckXWWWWWWNNNNKkk0OoodookKKXNNNX00XNKxkNWNXKOOkddOKKXNNNNNX0OkxkO00XX0dooooooooox0NWWMMMWKo::::::::::::::
K000KXXK00KXK0OOOOOOOO0K0KNXKXXXXXXXXXNNXXXXXXXXKKKKKKXNWMMMMWKxc;:::::::xNMMMWWNKO0XNWNkool::::cONWWWWNXXNNXOdx0kolooodO0KXXNXOkXNXkxKNNXKkkOxxxO00XNNNNNKkdxxkO0KXNOdoooooloood0NWWMMMWKo:::::::::::::
KK0KXNKK00KKK000K0OO000KKKXXXXXXXXXXNXXNXXXNNXXXXXXXXNWMMMMWKxc:::::::::oKMMMWWNXkdx0XNKxdkklcc:o0NNNNNNKKNX0xok0kolodddxO0KXXXOkKNXkdOXXXKkxOkOOkOOOKXNNNXOdoxxkkOKNXkdodxkdolood0NWWMMMWKo::::::::::::
000KXXK0KKKK0000K00KXXXXXXXXXXXXXXXXNNNNXXXXXXXXXXNWWMMMMWKxc;:::::::::cOWMMMWNXOdoodxOkdxKKkxxdkKNNNNNKOKXKkddx0klcoddddxO0KXXOx0NXOxk0XKKkxkk0X0kkxkKXNNX0kddxxxk0XNXOOKNNKkoooldKNWWMMMW0l:::;:::::::
00KK0K00KKKK0KKKKKKKXXXKKXXXXXXXXXXXXXNXXXNNXXXXNNWMMMMWXxc;:::::::::::xNMMMWWN0xooooooookXKOOOk0XXXXXKkkKKOxkxxOklcodxxxdxOKXKOk0XXOkkOKK0kkkk0NNKOkxkKXXXKOxdxkkxkKNWWWWWWNXOddolxKNWMMMMWOc::;;;:::::
KKKXK0KKKK0K0KKKKKKKKK0000000KXXKKXXXXXXXXXXXXXNWMMMMMNkl;;:::::::::::l0MMMWWNXkoooooooodOXKOOOO0XXXXKkxOKOkOK0kOkocldxxxxxk0KKOk0XKO00O0K0O0KOOXNX0OkkOKXXK0kxxkOkxONNWWWWWNNX0xdolxXWWMMMMNkc::;;;::::
KKKKKKKXXKKKKK0000000OO0KK00000KKKKKKKKKKKKKKXNWMMMMW0o:;:::::::::::::xNMMMWWN0dooooooood0NKOOOOKKKK0Oxk00OOXWXkkkdoodxkkkkkOKKOO0XK0KX00K0OKNKOOKXXKOO0O0XK0OkkkkOkkXNWWWWWNNNX0kdlckNWWMMMMXd:;;;;;:::
KKKKKKKKK000KK00000OOOO00KKK0K0000KKKKKKKKKKXNMMMMMNxc;;:::::::::::::l0MMMMWNXkoolldkxddkKNKOOkOKKKOkkkk00OKNNXOkkkxxdxkkkkkO000KKKK0XNXK000XXXNXXWWWNXXXKKK00O0KOOOkKNNWWWWNNNNX0kd:c0NWMMMMMKl:;;;;;::
XXXXXXXK000000000K00000000KK000000K0KKK000KXWMMMMWKo;;:::::::::::::::dNMMMMWN0doood0NNXKXNNKOOkOKK0kxkOO00OKXXX0kkkOOkkO000KKXXXNNNXNNWNNNNNWWWWWWWWWWWWWWNNNXXXNNK0OKXXNWWWNNNNNNKkc,dXWWMMMMWkc:;;,;;:
NXXXXXXKKKKKK000000000K000KKK00KKKK0KKK00KNWMMMMNOc;::::::::::::::::cOWMMMWWXkloodOXNWWWWWNKOkxOKKOkk0K000KNWWWNKOO0XNXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWNKKKKNNWWNNNNWWNKd,;ONWWMMMMXo:;;,,;;
NNNNNXKKKXXXXKKKKK000000000KKKKKKKKKKXK0KNMMMMMNx:;;::::::::::::;;::oXMMMMWWKdlodkKNNWWWWNNX0kxOKK0O0KNXKKNWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kdolc:cloxkKXXXK0XNWNNNNNWWWNOc,oKNWMMMMWOc;;,,',
NNNNNXKKKXXKKXXKKKK00000000KKXXKKKKKXXKXWMMMMWXo;;::::::::::::::;;::xNMMMMWN0oodk0XNNWWWWNNX0OkOKK00KNWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNKxc,......',,'',;lk0O0XNNNNNNNWWWN0o;:ONWWMMMMXd:;;,''
XXXXXKKKKKKKKKKKKKK000000000KKXXKKKKKXNWMMMMWKl;;::::::::::::::;;;:cOWMMMMWNkloxOKNNNNWWWNNXKOO0KKXNNWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXkc'.....''',cxOOkxl:dOk0XNNNNNNNWWWWKx:,oXNWWMMMWOc;;,''
KXXXK00000000KKKKKKKKKK0000KKKXXXXXKXNWMMMMW0l;;::::::::::::::;;;;;lKMMMMWWXdcdk0XNNNNWWWNXXK0XNNNN0Okdlccccllodk0XNNWWWWWWWWWWWWWWWWWWWWWWWWWXx,..'',;;:ll::xXXXX0dkOkKXNNNNNNWWWWWKkl,:ONWWMMMMKo;;;'.
KXXK000000000KKKKKKKKKKKK0KKKKKXXXKXNWMMMMW0c;;:::::::::::::::;;;;:dXMMMMWWXo:x0XNNNNNNWNNKKKXNN0d:'..............,lkXWWWWWWWWWWWWWWWWWWWWWWWWKxl::::;;clddlckNWWWXO000XXXXNNNWWWWWNKkd:;xXNWWMMMNx:;;,;
KKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKXXXXNWMMMMMKl;;;:::::::::::::::;,;;:xNMMMMWWKl;xXWWNNNNNNNNX00K0d;,:lloo;',,,,,',,'.,:dXWWWWWWWWWWWWWWWWWWWWWWWNNKdlooccoxkkxd0WMMWXKXKKXXXXNNNWWWWWWKkdlcxKNNWMMMWOc;;;;
XXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWMMMMMXo;;;:::::::::::::::;,,;;:kWMMMMWNKc,xNWWWNNNNNNNX0O0Ol:d0KKKk:;::;:::oolcdO0XWWWWWWWWWWWWWWWWWWWWWWWWWWKkkOOOO000O0NMWWXXNK0XXKKXNWWWWWWWWXkdxdx0XNWWMMWKo;;;,
XKKKKKKKK00OOOOO000KKKKKKKKKKKKKKXNWWWWWNx;;;::::;;;;;:::::::;,,;;:kNWWWWWN0c;dKNNNNXXXNNNNXOkOOxOXNWWKo:llllc;coookNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0000KKK00KNNNNXXX0KXX00NWWWWWWWWWNOddccOXNWWMMMXd:;;,
XXKKK0kxddooooooooddk0KKKKKKKKKkdxkkkkk0k:;;::::;'''',::::::;,',;;:okkk0NWNk,':dxxxxxxxkkO0KKkk00KNMMMWOdxkOkxdxkOkKWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKXXXXKXXXXXXXXKKKX0OXWWWWWWWWWWN0xx::kXNWWMMMNx:;;,
XKKOxoolllllllollllloOKKKKKKKKOddxxxxxxdc;;;::::;'..',;::::;,''';;:lddxONWXx,.;lddddddooooodk0O0KKNWWWMNKO00KK00000NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXXXXXXXXXKKX0OKWWWWWWWWWWWWXOxl:kXNWWMMWWk:;;,
K0xollllodxkkOOkkkxddOKKKKKKK0xodxxxxxdc',;:::::;'...,;:;;;,,''';;:lddx0NWXx,.;cx0KKK0Oxdollok00KXXNNNNNNK00KKKKKKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXXXXXXXKKKXKKK0k0NWNNWWWWWWWNNWKkockXNWWMMMWO:;;,
koccccldkOOOOOOOOOOOOOOOO0000xooxxO0kxo;.,;:::::;'...';;,,,,''.';;;cddx0WWXk;.;cxNWWWWWXkdolldOKKXXXXXXXXXXXXXXXNNNNNWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWNNNNNXXXXXXXXXKKKOk0NWWNXNWWWWWWNXNN0doOXNWWMMWWOc;;,
oc::ccokkkkkkkkkkkkkkkkkkkkOxoldxkKW0xl'.',;::::;'...',;;:;;;:c;;;;:odxKWWXk:,;:xNWWWWWW0ddlcoOKKXXXXXXXXXXXXXXXNNNNNNWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWNNNNNNNNXXXXKK0kkKNNWWXKNWWWWWWNXKXNOx0NNWWMMWWOc;,,
c::::lxkkkkxxxxxxxxxxxkkkkkkdlodx0WMXkl,..',;;;:c:;::okKK0kddxdc,;,;odxKWWXkc;;;dXWWWWNKkdddodOKKKKXXXXKKKKXXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXKKKK0KNXXWWK0NWWWNWWNX00XX0KXNWWMMWWO:;,,
c::::oxkkkxoccllllllldxkkkkdlcoxkXMMWKxc,,;lxk0KX0xxxONMWKxxxxo:,;,;ldkXWWNOl;;:oOOOOOxxdddk0K0O0KKKKXXXXXXXXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXNXKXWNKKNN00NWWWNNWNX0kOKXKKNWMMMWNkc;;,
c::::oxkkkxl::::::::cdkkkkxo:cdx0WMMMNOxddx0WMMMWKxddx0XKkxxxxd:,;,,cdkXWWNOo:;:ldddddddxO0XWWN0kk000KXXXXXXXNNNNNNWWWWWWWWWWWWWWWWNNNNNNNNNNNWWWWWWWWWWWWWWWNNNNNXNWX0KNXO0NWWNNNWNX0kkk0KKKNWMWWNx::;,
c::::oxkkkxdooooc:::cokkkkdc:cdONMMMMWKxdddx0XKK0xlcccdxddxkkxdl,,'';okNMWNOol::dOOkxddddkOKNWWNXOxk00KKXNNNNNNNNWWWWWWWWWWWNNXXX000kxOkxkkkkkKWWWWWWWWWWWWWWWWWWNXNNOkKNKk0NWWNXNNNX0kk0KKKKKXNWWXd;;,;
c::::ldkkkkkkkkdc:::cokkkxl::clxO00OOOxolccclxkkkdc::cooldxKXkxo;''.,lONMMNOdocckXXXX0xddddxKNWXNNKOkOKKXXXNNNWWWWWWWWWWWWWN0xxddooollllllllld0WWWWWWWWWWWWWWWWWWNXNKxxXX0k0NWWNXNNXKOk0XNNXXKKKXXKd:;,c
o:::::lxkkkkkkkdc:::cokkxoc::::ccccc::::::cccokkkdc::cllcdONWKxd:''.'ckNMMW0dollkKKXWN0ddddoxXWXKNWX0O0XNNNNWWWWWWWWWWWWWWWW0dlllllllllllooookXWWWWWWWWWWWWWWWWWNXXXOdkXXkk0NWWNXXNX0k0XNNWWWNXXKKOxl::x
xl:::::lodxxxxkdc:::coxkdl:::clllllllloolcc:cldkkdc:::c:cdXMMNOxo,...;kNMMW0doloxkKXNWXOdddolkNNK0NNN0kKNNNWWWWWWWWWWWWWWWWWN0doodddddxxkkkkOXWWWWWWWWWWWWWWWWWXOOXKxdOXKkk0NWWXXXNX00XNNWWWMMWWNXkdoodK
kxoc:::::ccllllc::::cdkxo::::lxkkkkkkkkxdc::::lxkxl:::::ckWMMMXkdc'..'dNWMW0dloooxOXNWNKkdddllOXKkONWXkxKNWWWWWWWWWWWWWWWWWWWNXOOOOOOOOOOO0KNWWWWWWWWWWWWWWWNKOdd0KOdx0XOxk0NWNXKXNX0KNWWWWWWWWWWKo;,cOW
kkxdolc::cccc:::::::ldkdc:::cdkkkkkkkkkkxl::::cdkxl:::::lONMMMW0xo;...cKWWW0olllxOOKXNNNKkddoclOXOd0XNKxdOXWWWWWWWWWWWWWWWWWWWWWNXKKKKKKXXNWWWWWWWWWWWWWWNX0xoookKOddk00kxkKNWNXKKXK0XWWWWMWWWWWNx:,,dNM
kkkkkxxdooooolllooddxxxdoooodxkkkxxxddddddooooodkxdolloodkXMMMMNXKx:'';xNWN0xxxk0K00KXNXXXK0OxokXKxxO0X0dodk0XNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOxollllx0OxddkKOdoxXWWNXKKXKXWWWWMMWWWWW0l;;l0MM
kkkkkkkkkkkkkkkkkkkkkkkkkxkkkxdollccc:::ccclldxkkdlcccldkk0WMMMMWKkl,.'cONKkddxxkxdddxkkkOKNNKkkKXOddx0XOoc;;clodx0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOxolllllodOOdddx00xddONWNX00KKXNWWMMMMWWWNXd;,c0WMM
kkkkkkkkkkkkkkkkkkkkkkkkkkkxolc::::::::::::::lxkkdc:::cdkkOXWMMMW0xd:'.;o00xoddddddolloolodk00OxOKKkddx0Kd:,,,,,,;cxO0KNNWWWWWWWWWWWWWWWWWWWWWWNX0Oxoccllllooxkxddddk0kddxKWWNK000KXWMMMMMWWWWNk:,;xNMMM
kkkkkkkkkkkkkkkkkkkk00kkkxdl:::::clooddooollcoxkkoc:::cdkkk0NMMMW0xxd:;lkO0kddddkKK0kxxdolodxkkxxOKOkxdxkdc,,,,,,,,;cllodxO0KXNNWWWWWWWWWWWNXKOkxddolcllllloxxdodxxdO0kdokNWWX00O0XNWMMWWWWWNNOl,;xNMMMM
kkkkkkkkkkkkkOKKOkkkKX0kxdc::::coxkkkkkkkkkkxxkkxoc:::cdkkkkKWMMW0xddooxocdxdddx0WMWNKK0xloodxOxdxOK0kddlcc:;::;,,,,:lcccccodxxkOO0KKXXXX0Okxddddddoclollld0XKOdddox0OkxxKNWN0OOkOKNWWWWWWNNNOl,:kNMMMMM
kkkxxkkkkkkkkk00kkkkKWNK0kxoc:cdkkOOOOOOOkkkkkkkxoc:::cdkkkkOXWWNOooodkkc,;coddd0WMMWXKKkllodkKOdoxOK0kdoc::col:,,,,;cccccccoddddddddxxxxdddddxxxxkxllllloKWMMWXOxdO0xdxOXWNK0OOO0KNWWWWWNNX0o;:OWMMMMMM
kkkkxxkkkkkkkkkkkO0KXWWN0kdlc:oxkkkkkkkkkxxxxxkkkoc:::cdkkkkk0NMW0xxxx0N0c,';lddOWMWMWKkdllloONXkooxkO0xdol:cddl;;cc:cccccccoxxdddddddxkOxxdxxxxx0NNKxoloOWMMMWXKOO00OkkKNNKOOO0KXXNWWWNNX0xc;lOXNWMMMMM
kkkkkxxkkkkkkkkkkOOOOKWKo::::cdkkkkdllllllclloxkkoc:::cdkkkkxk0NW0xxxx0WWKo'.;ldxO000OxollloxXWWXxoooxkoloodoooollodolllcccdKX0kxxxxxkKWWN0kxxxx0WMMMN0dxKNXNNXXXK0OkOO0XNX0OkOXXKKNWNNXKOxlcxO0KKXWMMMM
kkkkkkkkxkkkkkkkkkkkk0NXd::::ldkxxxoc::::::::lxkkdc:::cdkkkxkxkKN0xxxx0WMMXo'.,codddddddddxO0KNWNKxooollccok0xdkOkxdddxoccxXMMWX0kkxOXWMMMMNK0O0NWWNNXX00XNNWWMNK0OOOO0KXX0Ok0XWXKXNNX0kl:lx0XK00KKXWMMM
kkkkkkkkxO0Okkkkkkkkkk0Kd::::cdkkxxdooool::::lxkxdc:::cdkkkkkkkk0Oxxxx0WMMWOl,.'cxkkxdddodxk00KNWN0xdl::cld0XKKKKkdoodxxodKNWWWWNKOOXNWWNNXKKKKXNNWNNNWWMMMMMMNKOkOKKKKXX0kk0XWNXKXXKxl::ldOKXXKkkKXNNWM
kkkkkkkkkKNXK0OkkkkkkkkOdc::::oxkkkkkkkxo::::lxkkdc:::cdkOOOOOkkkddxxx0WMMW0dc;',lOKKkddolcokOOKXNNOdl:::cok0000Okddoook0KXXXNNNNNNNNNWWWNNNXXNNWMMMMMMMMMMMMNKK0k0KKKKKKOO0NNNXK0koc;;oO0kk0XXXKO0XKKXN
kkkkkkk0KXWNKOkkkkkkkkkkdc::::coxkkkkxkxo::::lxkkdc:::cdkOkkkkkkdlldxxKWMMW0ollccccdOKkdollldkOO0XXOdoc:::cloddddddxxxxkXMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMWWWXXXKXXXXK0OkOKXXK00Oxo:cdO000OkOKKKXXNNNXKK
kkkkkkkkkkKXOkkkkkO0Okkkxdc::::cldxxkxxxo::::lxkkxl::::cdxkkkkkxl::cdONMMMWOllllx0klcoddollloxkkO0OxoolclloooxkO00OkxxddONMMMMMMMMMMMMWXKXWWMMMMWXXWWMWWWWWWWNNXXNNXKK0OO00Odloxdoxk0XXXXXNNXXKKKXXNWWWN
kkkkkkkxxkO0kxkkkkOK0kkxkxdl::::::clllllc::::lxkkxdl::::cllooolc::::o0WMMMNkllclkKKOkoc:;:clldkOkkdlooooxOOkk0KKNWWKxdddxKWMWWMMWWWWWWN0kOO0XWWWWKKNWWWNNNWNNXXNNXXKOxdolcloccx00KXXXNWWWMMWWNNNNXKKXWMM
xxkxxkkkkxkkkkkkkkkkkkkkkkkxdlc::::::::::::::oxkkkxxoc:::::::::::ccoxOKWMWKxlccokK0O00Oko;,:lcokOxccccldOKXK0KXXXNWXkddddkXWWWWWWWWWWWNX0OO0XNNNK0XNNNXXXXXKKXXXK0Oxdc;;:codxOXWWNNWWMMMMMMMWWNWWNNXKNWM
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdolc::::::cclodxkxkkxkxdolc:::::ccloxxkkkKWN0koloxk0O0XNNXXklco:;lxxllllox0KXXXKKXNNNN0kxkkkKNNNNNNNNNNNNNNNNNXXKOk0XNXK000OxkKX0kkdccdoldOKK00XWWNWWMMMMMMMMMWWNNNNNNNXNM
====================================================================================================================================================================================================*/

#include <stdio.h>
#include <stdlib.h>

struct node{
	int data;
	struct node* next;
};

typedef struct node Node;

Node* stack_init(void){
	// init stack as null empty stack.
	return NULL;
}

Node* stack_push(Node* top, int push_item){
	Node* curr = (Node*) malloc(sizeof(Node));
	curr->data = push_item;
	curr->next = top;
	//top = curr;
	return curr;
}

Node* stack_pop(Node* top){
	// return pop out value.
	int rtn = top->data;
	Node* tmp = top;

	if(tmp==NULL){
		return NULL;
	}

	top = top->next;
	free(tmp);

	return top;

}
int stack_isEmpty(Node* top){
	return (top==NULL);
}
void list_stack(Node* top){
	Node* curr = top;
	printf("print stack\n");
	while(curr){
		printf("%d\n", curr->data);
		curr = curr->next;
	}
}


int main(){

	Node* stack = stack_init();

	int input[] = {1,2,4,5,6,8,2,4,2,1,6,7,9};
	
	for(int i=0;i<13;i++){
		stack = stack_push(stack, input[i]);
	}

	stack = stack_pop(stack);

	if(stack_isEmpty(stack)){
		printf("empty");
	}

	list_stack(stack);
	return 0;
}
